---
- name: Add PPA for Firefox Developer Edition.
  become: yes
  apt_repository:
    repo: ppa:ubuntu-mozilla-daily/firefox-aurora
    state: present

- name: Install Firefox Developer Edition
  become: yes
  apt:
    name: firefox
    state: present
